### ISSUE TITLE
Issue with iA Writer docs

### ISSUE THREAD

**Issue by pixelstrolch** [mattcone/markdown-guide#103]
iA Writer supports highlight.

**Comment by mattcone** [comment]
Thanks for reporting this! I believe this has been fixed in https://github.com/mattcone/markdown-guide/pull/116.

**Comment by arsinam80** [comment]
در تاریخ پنجشنبه ۷ ژوئیهٔ ۲۰۲۲،‏ ۷:۵۹ Matt Cone ***@***.***>
نوشت:
