### ISSUE TITLE
Issue with Discord docs

### ISSUE THREAD

**Issue by fixator10** [mattcone/markdown-guide#114]
Discord has support of links, but only in certain cases.

Links do work in embeds (in fields where markdown works), and in webhook messages/slash commands
![message/webhook](https://moeka.is-a-good-waifu.com/9pE8PFG.png)
![slash command's webhook with title](https://moeka.is-a-good-waifu.com/49NLVCb.png)

**Comment by mattcone** [comment]
Thanks for the heads-up! I've pushed https://github.com/mattcone/markdown-guide/commit/9f87bca732c6e37996d2249d65426f9ecbf59bf1 to address this.
