### ISSUE TITLE
Issue with MacDown docs

### ISSUE THREAD

**Issue by CyberPlutus** [mattcone/markdown-guide#118]
I get "     “MacDown” cannot be opened because the developer cannot be verified." When trying to install 

Trying to install in my iMAC and I get the above message ??

**Comment by spcified** [comment]
Take a look at [Macdown-issue-1249](https://github.com/MacDownApp/macdown/issues/1249)

**Comment by mattcone** [comment]
Hey there! This repository isn't affiliated with MacDown. I'd recommend filing an issue over at the MacDown GitHub repository: https://github.com/MacDownApp/macdown. Thanks!
