### ISSUE TITLE
Doc for Slack codeblock markdown is wrong

### ISSUE THREAD

**Issue by chosig** [mattcone/markdown-guide#122]
Codeblock is supported staring and ending with 3 backticks, the ticks can be on it's own line or on the same line as the start/end of the text

\```this
is a
codeblock```

\```
this
is a
codeblock
\```

**Comment by mattcone** [comment]
Hey, thanks for reporting this! I've looked into this and I believe the documentation is correct as currently written. There are essentially three ways of doing code formatting in Markdown — what I call code (one backtick), code blocks (indented, defined in the legacy spec), and fenced code block (three backticks). The documentation currently and correctly states that fenced code blocks are supported in messages and posts. It's just that code blocks (created using indentation) are not. See screenshot below. 

![image](https://user-images.githubusercontent.com/40424/189401239-c507c131-2d48-4ea5-9054-4a0f6e9eb2fe.png)

Perhaps there's a better way of representing this on the website to make it less confusing. I'll keep thinking about how to potentially redesign the tables on these pages. Anyway, thanks again for reporting this.
