### ISSUE TITLE
_tools/wiki-js.md: "Dendron" typo

### ISSUE THREAD

**Issue by mrienstra** [mattcone/markdown-guide#125]
>    notes: "You can link to other notes in Dendron by using the `[[Link name|filename]]` syntax."

-- https://github.com/mattcone/markdown-guide/blob/master/_tools/wiki-js.md?plain=1#L31

**Comment by mattcone** [comment]
Thank you! Fixed in https://github.com/mattcone/markdown-guide/commit/3d43f369ff5f034847354496e25b9c86a64f520c.
