### ISSUE TITLE
Recommend against using emphasis in middle of a word

### ISSUE THREAD

**Issue by huyz** [mattcone/markdown-guide#135]
As you say, "Markdown applications don’t agree on how to handle underscores in the middle of a word" and "Markdown applications don’t agree on how to handle underscores in the middle of a word".  But instead of recommending to use asterisks, I recommend that you recommend to not use this feature at all.

I think this capability is the most useless features of the original Markdown.  I can't think of any use cases at all.  And I can think of many times when having a coding keyword such as `my_code_variable` is rendered wrong because I didn't put the word inside of backticks.  This hasn't happened to me much but I imagine regular expressions that aren't enclosed in backticks would also be a problem.  This is an abomination and all Markdown renderers should simply drop this design bug.

**Comment by mattcone** [comment]
I appreciate this suggestion! You make a good point, and I know a lot of people share this view. But after thinking about this for a while, I've decided to close this issue without action. 

We don't have control over the availability of the feature in the original Markdown spec and various implementations. That probably goes without saying, but it's an important consideration here. Whatever personal reservations we may have regarding this feature, the fact remains that it's available and supported, and it does need to be documented in some capacity. 

Regarding the documentation, it's true that I make recommendations that relate to compatibility. However, making usage recommendations based on a feature's practical application (or lack thereof) feels like a bridge too far. My personal opinion is that we should let readers draw their own conclusions.

That said, you're absolutely right that this "feature" (bug?) causes a lot of confusion. I'm honestly not sure how to address the numerous issues related to emphasis in the middle of a word. Something to continue thinking about. I've been playing around with the idea of creating a troubleshooting section — this seems like something that could fit in there.

I hope this sheds some light on my decision-making process here. Thanks again for opening this issue and for all of your suggestions over the past several weeks.

**Comment by huyz** [comment]
I appreciate your detailed reply. Thank you for considering and explaining your thinking
