### ISSUE TITLE
update to https://www.markdownguide.org/getting-started#additional-resources

### ISSUE THREAD

**Issue by rondfw** [mattcone/markdown-guide#15]
Hello.  I'm new to the Markdown world, so thanks for putting this resource together.  I've been clicking around and on page https://www.markdownguide.org/getting-started#additional-resources you list Codecademy’s Mastering Markdown course: A free and interactive lesson that allows you to experiment with Markdown.

The intended page is:  https://www.codecademy.com/courses/web-intermediate-en-Bw3bg/0/1 
 but the resulting page, https://www.codecademy.com/catalog/subject/all?composer_redirect=course, says:  **"As of July 5, 2018, this course is no longer supported. Check out our catalog for the latest course offerings."**

It would appear that https://www.markdowntutorial.com/ is the way to go.

Cheers and thanks again,

Ron

**Comment by mattcone** [comment]
Hey Ron! Thanks so so much for reporting this! I removed the link to the Codecademy course in  852c5cb.
