### ISSUE TITLE
Issue with Discord docs: Discord does not actually support links.

### ISSUE THREAD

**Issue by mattbisme** [mattcone/markdown-guide#163]
After testing out the standard markdown link:

```markdown
[discord supports links?](https://www.markdownguide.org/basic-syntax/#links)
```

It would seem that it does not. Or at least not for me in my own server. If there is some trick to this, it is not known to me.

**Comment by mattcone** [comment]
Hey, thanks for reporting this and sorry about the delay. I did some investigating and it appears that you're correct — links (what Discord refers to as "link masking") are not currently supported. See https://github.com/discord/discord-api-docs/issues/6088. I can't tell if this is temporary. 

I've made the update in https://github.com/mattcone/markdown-guide/commit/013a250cd20543c62fb5805cfabc98406a62fa33. I'll try to keep an eye on this and update the documentation when it's been resolved.
