### ISSUE TITLE
Issue with Discord docs

### ISSUE THREAD

**Issue by MallyFractal** [mattcone/markdown-guide#169]
Ordered lists and nested ordered lists are supported by Discord, despite Markdown Text 101 not showing such.

![ordered-list](https://github.com/mattcone/markdown-guide/assets/29518670/4cadb0c1-bce6-4c18-ade1-91c10878b2db)

**Comment by mattcone** [comment]
Thanks for reporting this! I've made the update in https://github.com/mattcone/markdown-guide/commit/2561f1bbf06abddbbadb9ac4bdfba6847b3a9be7.
