### ISSUE TITLE
Issue with Logseq docs

### ISSUE THREAD

**Issue by ewayte** [mattcone/markdown-guide#171]
"There’s not currently a mobile app, but there is an option to use git for note storage and link the repository with Logseq."  Logseq does have mobile apps available for iOS and Android.  [https://logseq.com/downloads](url)

**Comment by mattcone** [comment]
Thanks for reporting this! I've fixed this in https://github.com/mattcone/markdown-guide/commit/e858d37cf77a1bcbfbf1afc929c3c667590993d3.
