### ISSUE TITLE
How highlight line in code block

### ISSUE THREAD

**Issue by oim37** [mattcone/markdown-guide#176]
Hello,

I use winter cms and built-in markdown editor.
In guide i'm not find how highlight some lines in code block.

I try ** and == but it working only in normal, not in code block.

Help please how i can make it?

**Comment by mattcone** [comment]
Hello! I'm sorry, I'm not familiar with Winter CMS. Perhaps you could check the docs or open an issue in the Winter CMS repository? https://wintercms.com/
