### ISSUE TITLE
Issue with Discord docs: Discord Markdown Link Supported

### ISSUE THREAD

**Issue by 0Ky** [mattcone/markdown-guide#178]
Discord supports [Masked links](https://support.discord.com/hc/en-us/articles/210298617#h_01H53FJBNB9B5RT9M1M9V1EQ7W) using `[title](https://www.example.com)`, there are limitations such as not being able to use it with an emoji character in the title.

Edit: When testing the same markdown syntax from issue #163, it works as intended:
![image](https://github.com/mattcone/markdown-guide/assets/16103757/772b5a85-708d-42ab-8038-74d369fbbb6f)
Using public test build version 239360 (427cfe2)

**Comment by Starmania** [comment]
At least, partially supported, because you can't put anything you would like in it (example, native emoji)

**Comment by Starmania** [comment]
`[16⭐](https://github.com/Glazelf/NinigiBot/stargazers)` Still not work
