### ISSUE TITLE
Navigation Bar overlapping with content in Basic Syntax Docs

### ISSUE THREAD

**Issue by akshatnavlani** [mattcone/markdown-guide#182]
In the Basic Syntax Docs, the navigation bar is overlapping the content under "Link Best Practices"

(https://www.markdownguide.org/basic-syntax/#link-best-practices)

![Screenshot 2023-12-11 143510](https://github.com/mattcone/markdown-guide/assets/144344423/70958170-c096-4d4d-8c61-dbabbcc704ab)

Also I would love to be assigned this issue

**Comment by mattcone** [comment]
Thanks for reporting this! I believe I've fixed this in https://github.com/mattcone/markdown-guide/commit/1002d26a3235e2e00b83560902cc424f4e196d88.
