### ISSUE TITLE
Issue with Madoko docs

### ISSUE THREAD

**Issue by PastTenseOfDraw** [mattcone/markdown-guide#194]
Issuewith Madoko's website:  "https://www.madoko.net"

"This site can’t be reachedThe webpage at https://www.madoko.net/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID"

**Comment by mattcone** [comment]
Thanks for the heads-up on this one! I've switched the primary links to the GitHub repository in https://github.com/mattcone/markdown-guide/commit/ed228787b98d3ccd74521c805a5c47f65bb07b21. Hope they can fix their DNS or renew their domain name soon. 😄
