### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Mrashes** [mattcone/markdown-guide#196]
https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/escaping-characters.md#escaping-backticks

Doesn't link to anything - not sure where it should go

**Comment by Mrashes** [comment]
That said - I'll fix it if I know how to escape backticks (literally trying to find out currently)

**Comment by mattcone** [comment]
Hmm... it should point here: https://www.markdownguide.org/basic-syntax/#escaping-backticks

Were you trying to access the link from markdownguide.org or the GitHub repository?

**Comment by Mrashes** [comment]
@mattcone Ah, I was doing it in the [github repo](https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/escaping-characters.md?plain=1#L35) - and assumed it would still work.

Its probably best to keep it relative rather than absolute then.

**Comment by mattcone** [comment]
@Mrashes: Thanks for responding, and sorry for the confusion. I'm planning on redesigning the file structure soon, so that work should resolve this issue.
