### ISSUE TITLE
Links to libraries that support this documented flavor of markdown?

### ISSUE THREAD

**Issue by greggman** [mattcone/markdown-guide#20]
I tried some of the features mentioned in your docs and they didn't work on the library I was using. It would nice to know which libraries I can use that support the flavor of markdown documented here.

**Comment by mattcone** [comment]
Hey, thanks for reporting this! I've started work on a tools directory that will describe what applications support which features:

https://www.markdownguide.org/tools/ 

This is going to take some time to build out, but eventually there will be lists showing exactly which applications support certain features. Thanks again for reporting this.
