### ISSUE TITLE
Blockquote style is broken

### ISSUE THREAD

**Issue by jLouzado** [mattcone/markdown-guide#22]
- While explaining the use of block-quote syntax, the rendered text isn't formatted differently.
- this might make it confusing for someone unfamiliar with HTML, or coming from a non-web background.

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/2016685/61872530-31fcf400-af01-11e9-9b5a-1fed15f80372.png">

**Comment by mattcone** [comment]
Someone else also reported this via the contact form:

> Just want to let you know that part of the Basic Syntax Guide isn't displaying properly on my computer. In the Blockquotes section, when is says, "The rendered output looks like this:", the following text does not show any difference. I especially noticed it in the Nested Blockquotes section; the "Dorothy...with wood" lines do not display any differently than the preceding sections. I'm on Win10, Firefox (Quantum) 67.0.4 (64-bit) Thanks! Otherwise the guide has been a great reference for me.

**Comment by jLouzado** [comment]
@mattcone maybe a `bug` label would be more appropriate than `enhancement`? This doesn't seem like a "nice to have", it's actually misleading for people who are trying to learn markdown.
