### ISSUE TITLE
Issue with MacDown

### ISSUE THREAD

**Issue by davidmichael47** [mattcone/markdown-guide#25]
Received message that macdown file was corrupted and could not be run.
Installed from both Homebrew and downloaded  zip file.
Macbook Air
Mac OS Mojave 10.14.5

**Comment by mattcone** [comment]
Hi @davidmichael47! I think you might have filed this in the wrong place. This is the repository for the Markdown Guide docs only. The GitHub repo for MacDown is over at https://github.com/MacDownApp/macdown — I'm sure they'll be able to help you over there. Thanks, and good luck.
