### ISSUE TITLE
Update to tools

### ISSUE THREAD

**Issue by maia-sh** [mattcone/markdown-guide#27]
Thanks for this great resource!

Here are a few additional Markdown tools:

Zettlr: https://www.zettlr.com/

Byword: https://bywordapp.com/

nvALT: https://brettterpstra.com/projects/nvalt/
nvUltra (replacement to nvALT): https://nvultra.com/

**Comment by schultzter** [comment]
I would also like to add a tool. 

Madoko: https://www.madoko.net/

Sorry, I'm not in a position right now to clone the repository and make the changes myself. 

Thanks

**Comment by mattcone** [comment]
Thank you! I've added these to the new wiki page I created (https://github.com/mattcone/markdown-guide/wiki/Markdown-tool-directory).
