### ISSUE TITLE
Issue with Notion docs (highly opinionated but still :D )

### ISSUE THREAD

**Issue by eleijonmarck** [mattcone/markdown-guide#30]
I honestly feel that you cannot change the rules of how to write markdown. Please do not "reinvent" things.

notion
- toggle : >
- qoute: "

markdown:
- qoute: >

I love the product for everything, but the fact that you are willing to change markdown syntax makes me feel like you want to invent too much and therefore I am not able to be as portable to anything else. I just want to be a ravid fan because I want, not because I am "stuck" with how I write the markdown.

**Comment by mattcone** [comment]
Hi @eleijonmarck! I think you might have filed this in the wrong place. This is the repository for the Markdown Guide docs only. You might want to consider contacting Notion's support with this feedback. Thanks, and good luck.
