### ISSUE TITLE
Issue with Notion docs

### ISSUE THREAD

**Issue by lishouxian** [mattcone/markdown-guide#33]
```python
    my codes
```
this not support

**Comment by lishouxian** [comment]
'''
```python
    my code
```
'''
not support

**Comment by lishouxian** [comment]
` ` `python
    my codes
` ` `

**Comment by lishouxian** [comment]
*```*  python
codes
*```*

**Comment by lishouxian** [comment]
![image](https://user-images.githubusercontent.com/16477004/77844741-9c2a0f00-71db-11ea-8abe-ccf23a3ab604.png)

**Comment by mattcone** [comment]
Hi! Thanks for opening this issue. Yes, you are correct — Notion does not support syntax highlighting. I checked the Notion page and this is already correctly listed:

> Syntax highlighting is not supported.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/40424/77851373-18016880-7196-11ea-9bc3-8eced4d7afef.png">
