### ISSUE TITLE
Issue with Todoist docs

### ISSUE THREAD

**Issue by FarhadGSRX** [mattcone/markdown-guide#50]
Hi there, 

I don't believe table formatting works anymore in the comments section of Todoist tasks.

(I'm on Windows, in Chrome, on the Todoist WebApp)

Cheers, and thanks for your great documentation!

**Comment by chnuessli** [comment]
Hi @FarhadGSRX 
I can agree on that. It's since the new version of Todoist.
Maybe you want to report an issue here: https://todoist.com/de/contact

**Comment by mattcone** [comment]
Thanks for reporting this. @chnuessli fixed it in #51
