### ISSUE TITLE
Some Markdown Code isn't correctly displayed on website

### ISSUE THREAD

**Issue by chnuessli** [mattcone/markdown-guide#54]
For example: https://www.markdownguide.org/extended-syntax/#strikethrough

Maybe it's a problem by HTML formatting?

**Comment by mattcone** [comment]
Would you mind sharing a screenshot? I'm not seeing anything out of the ordinary on my end.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/40424/100364215-0a1d1500-2fbb-11eb-9a00-0ea47e66cb24.png">

**Comment by chnuessli** [comment]
Okay, right now it looks good to me. Maybe a problem with rendering on the browser. I close this issue
