### ISSUE TITLE
Issue with Dillinger docs

### ISSUE THREAD

**Issue by CodeBlooded88** [mattcone/markdown-guide#63]
I was able to access dillinger.io yesterday for a class project however today I am unable to. It says that my computer can connect to it, however the host is not responding.

**Comment by chnuessli** [comment]
Dillinger.io is not a product of this repository. In heee, it just handles how you can use it and as an example online editor. Your problem can't be solved in here, i am sorry

**Comment by chnuessli** [comment]
Today, the editor works fine..

**Comment by mattcone** [comment]
@CodeBlooded88: @chnuessli is right — we don't control Dillinger. If you have problems in the future, feel free to open an issue in Dillinger repository (https://github.com/joemccann/dillinger). Cheers!
