### ISSUE TITLE
PDF Sheet

### ISSUE THREAD

**Issue by folarinmartins** [mattcone/markdown-guide#65]
I find this resource the ultimate markdown cheatsheet. Can we have it as PDF, please? Good work

[![Appreciated](https://miro.medium.com/max/700/1*VcHVCyRSAOF3V6Ldi0iXOQ.jpeg Markdown)](https://miro.medium.com/max/700/1*VcHVCyRSAOF3V6Ldi0iXOQ.jpeg Thanks)

**Comment by mattcone** [comment]
Hi @folarinmartins. I appreciate the suggestion! This is something I've considered in the past. I'm not sure a PDF is something I want to prioritize at this point, but I'll keep it in mind and possibly revisit it in the future. Thanks!
