### ISSUE TITLE
markdown-cheat-sheet.md asset file Image link example references file that doesn't exist

### ISSUE THREAD

**Issue by DavidHartman-Personal** [mattcone/markdown-guide#68]
The assets/markdown-cheat-sheet.md asset file Image link example references file that doesn't exist.  I checked the images/ directory in case it was there but did not find it.  

```
### Image

![alt text](image.jpg)
```

**Comment by stevepopovich** [comment]
I have the same issue with `/link`. Really disappointing.

**Comment by mattcone** [comment]
Thanks for reporting! This has been fixed in https://github.com/mattcone/markdown-guide/commit/f95372614b54798297e9bccdec6aeeabb948ba65.
