### ISSUE TITLE
Issue with Boostnote docs

### ISSUE THREAD

**Issue by dayer4b** [mattcone/markdown-guide#69]
It is indicated that boostnote does not support some markdown features.  I believe the items listed as unsupported are incorrect.

I tested the following in boostnote and they all appear to be working as expected in BoostNote version 0.15.3:

* Footnotes
* Definition Lists
* Emoji (shortcodes)
* HTML

I agree with your assessment of the "Heading IDs" feature.  It does not appear to be supported.

thanks!

**Comment by mattcone** [comment]
Hey, thanks for opening this. I just tested again in the web-based version (apps aren't opening in macOS Big Sur) and as far as I can tell, footnotes, definition lists, and emoji shortcodes are still unsupported. I do see that HTML is working, so I've updated that in https://github.com/mattcone/markdown-guide/commit/edacc718c3db694267fe3ebeea1ce7f358f1eadd.
