### ISSUE TITLE
Issue with Notion docs

### ISSUE THREAD

**Issue by stevepopovich** [mattcone/markdown-guide#72]
How do I post a link in Notion? You say [here](https://www.markdownguide.org/tools/notion/) to use `/link` instead of Markdown, but `/link` doesn't look like it is there anymore. 

I just want this:
![image](https://user-images.githubusercontent.com/3252375/118493165-ce077900-b6ee-11eb-9916-32621c2408fc.png)
to not link to an internal page, but an external page somewhere else on the internet. Thanks!

**Comment by mattcone** [comment]
@stevepopovich: Thanks for opening the issue! I checked this out and I agree with you — I can't find a way to add external links. For now, the best solution I can come up with is adding a note better describing the current behavior (`/link` only works for internal links), but I'm open to other suggestions. The note has been added in https://github.com/mattcone/markdown-guide/commit/3732566f2f71ab6018fa750a3957b0ecd418ef7f
