### ISSUE TITLE
Barcelona people speak Catalan

### ISSUE THREAD

**Issue by toddthegeek** [mattcone/markdown-guide#76]
> People in Ciudad Juárez speak Spanish just like the people in Barcelona, but there are substantial differences between the dialects used in both cities.

So my wife speaks Spanish natively (she's from Mexico City).  We went to Barcelona.  All the signs were in Catalan.  Spanish was not the first language they spoke, and some people would not speak Spanish (they call it Castilian in Spain).

> The region of Catalonia has two official languages. Spanish and Catalan, of which are both spoken. In offices and schools, **Catalan is the dominant language**.

[Barcelona's languages](https://www.barcelona.de/en/barcelona-languages.html)

I would consider changing to maybe British English vs American English or Southern USA vs Northern USA in future revisions.  

Just my 2 cents.

**Comment by mattcone** [comment]
Thanks for reporting this! I've updated this reference in https://github.com/mattcone/markdown-guide/commit/ed34adfe191aa16ff364d84dd4522f07446df683.
