### ISSUE TITLE
Add HedgeDoc to tool list

### ISSUE THREAD

**Issue by mrdrogdrog** [mattcone/markdown-guide#78]
I'm one of the devs that work on [HedgeDoc](https://HedgeDoc.org). Please add our project to the tool list. It's a community driven hard fork of the Codimd that you already have in your list and was once also called CodiMD. If you want to know more about our name confusion then feel free to read about it on our [history page](https://HedgeDoc.org/history).

**Comment by mattcone** [comment]
Thanks for opening this issue! I didn't know about this project. I've added a new page for HedgeDoc in https://github.com/mattcone/markdown-guide/commit/6e2af138b5d4b6b91b5303a854fd58236a749b41.
