### ISSUE TITLE
cheat-sheet.md Preview Problems

### ISSUE THREAD

**Issue by ymart1n** [mattcone/markdown-guide#97]
Hi, line 115 in cheat-sheet.md breaks markdown preview on GitHub and in other Markdown previewers. Deleting the line fixes the problem. Would like to make a pull request if you think it's worth fixing. Thank you.

**Comment by mattcone** [comment]
Please do. Thanks!

**Comment by ymart1n** [comment]
Thanks! A pull request has been made.

**Comment by mattcone** [comment]
Fixed in https://github.com/mattcone/markdown-guide/pull/98
