### ISSUE TITLE
Interpretation of nested emphasis

### ISSUE THREAD

**Issue by BigBadaboom** [mattcone/markdown-guide#99]
The [CommonMark spec](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis) says that when nesting bold and italic:

> An interpretation `<em><strong>...</strong></em>` is always preferred to `<strong><em>...</em></strong>`.

However your examples have it the other way round.

Note this was a change in version 0.28 (2017) of the spec. Earlier versions had it the other way round.

**Comment by mattcone** [comment]
Hey, thanks for opening an issue! I researched this a bit and I admit that I'm scratching my head a bit on this one.

Not sure if I'm understanding this correctly (and not that it matters much at this point), but the order (and the change) appears to be arbitrary (?). See https://github.com/commonmark/commonmark-spec/commit/0e5e95eb7fcc973128d3a2a8cddf221f3825c156

In any case, https://babelmark.github.io/?text=This+text+is+***really+important*** is showing that it appears to be split about 50/50 among implementations. I guess I could add a note saying that CommonMark-compliant implementations switch the order. Do you think that would that be useful for readers?

**Comment by mattcone** [comment]
Thanks again for opening this issue. I've implemented a fix in https://github.com/mattcone/markdown-guide/commit/830cf88f460358b8b8461ce7a94c39173be637ff.
